builders:
  - script
triggers:
  cron: "@weekly"
slack:
  room: "eduid-builds"
pre_build_script:
  - "docker pull docker.sunet.se/eduid/redis:latest"
  - "docker pull docker.sunet.se/library/etcd:v3.3.12"
  - "docker pull docker.sunet.se/eduid/mongodb:latest"
  - "docker pull neo4j:4.0-enterprise"
environment_variables:
  NEO4J_VERSION: "4.0-enterprise"
script:
  - "python3.8 -m venv venv"
  - ". venv/bin/activate"
  - "pip install -U pip setuptools wheel mypy"
  - "pip install --index-url https://pypi.sunet.se -r requirements/test_requirements.txt"
  - "pip freeze"
  - "make test"
  - "make typecheck"
clean_workspace: true

extra_jobs:
  - name: eduid-backend-update-deps
    builders:
      - script
    pre_build_script: null
    triggers:
      github_push: false
      cron: "@daily"
    script:
      - "python3.8 -m venv venv"
      - ". venv/bin/activate"
      - "pip install -U pip setuptools wheel pip-tools"
      - "touch *.in"
      - "make update_deps"
