builders:
  - script
upstream:
  - eduid-userdb
  - pysmscom
  - eduid-common
triggers:
  cron: "@weekly"
slack:
  room: "eduid-builds"
python_module: eduid_msg
python_source_directory: eduid_msg
clean_workspace: true
publish_over_ssh:
  - pypi.sunet.se

extra_jobs:
  - name: eduid-msg-docker
    builders:
      - docker
    docker_name: eduid/eduid-msg
    managed_scripts:
      - docker_build_prep.sh
      - docker_tag.sh
    triggers:
      github_push: false
      cron: null
    upstream:
      - eduid-docker-python3env
      - eduid_msg

script:
  - "python3.7 -m venv venv"
  - ". venv/bin/activate"
  - "pip install -U setuptools wheel mypy"
  - "pip install --index-url https://pypi.sunet.se -r test_requirements.txt"
  - "pytest"
  - "mypy --ignore-missing-imports eduid_msg"
  - "python setup.py sdist bdist_wheel --universal"
