builders:
  - python
triggers:
  cron: "@weekly"
slack:
  room: "eduid-builds"
python_module: eduid_lookup_mobile
python_source_directory: eduid-lookup-mobile
clean_workspace: true
publish_over_ssh:
  - pypi.sunet.se

extra_jobs:
  - name: eduid-lookup-mobile-docker
    builders:
      - docker
    docker_name: eduid/eduid-lookup-mobile
    managed_scripts:
      - docker_build_prep.sh
      - docker_tag.sh
    triggers:
      github_push: false
      cron: null
    upstream:
      - eduid-docker-pythonenv
      - eduid-lookup-mobile
