builders:
  - script
upstream:
  - eduid-userdb
  - eduid-common
triggers:
  cron: "@weekly"
slack:
  room: "eduid-builds"
script:
  - "virtualenv venv"
  - ". venv/bin/activate"
  - "pip install -U setuptools"
  - "pip install --index-url https://pypi.sunet.se -r requirements/testing.txt"
  - "nosetests"
  - "python setup.py sdist bdist_wheel --universal"
publish_over_ssh:
  - pypi.sunet.se
clean_workspace: true

extra_jobs:
  - name: eduid-webapp-docker
    builders:
      - docker
    docker_name: eduid/eduid-webapp
    managed_scripts:
      - docker_build_prep.sh
      - docker_tag.sh
    triggers:
      github_push: false
      cron: null
    upstream:
      - eduid-docker-pythonenv
      - eduid-webapp
