builders:
  - python
upstream:
  - eduid-userdb
  - eduid-common
triggers:
  cron: "@weekly"
slack:
  room: "eduid-builds"
python_module: eduid_webapp
publish_over_ssh:
  - pypi.sunet.se
clean_workspace: true
