builders:
  - script
upstream:
  - eduid-userdb
  - eduid-common
  - eduid-action
triggers:
  cron: "@weekly"
slack:
  room: "eduid-builds"
pre_build_script:
  - "docker pull docker.sunet.se/eduid/redis:latest"
  - "docker pull docker.sunet.se/library/etcd:v3.3.12"
  - "docker pull docker.sunet.se/eduid/mongodb:latest"
  - "docker pull neo4j:4.0-enterprise"
environment_variables:
  NEO4J_VERSION: "4.0-enterprise"
script:
  - "python3.7 -m venv venv"
  - ". venv/bin/activate"
  - "pip install -U setuptools wheel mypy"
  - "pip install --index-url https://pypi.sunet.se -r requirements/testing.txt"
  - "pip freeze"
  - "make test"
  - "make typecheck"
clean_workspace: true

extra_jobs:
  - name: eduid-webapp-docker
    builders:
      - docker
    docker_name: eduid/eduid-webapp
    managed_scripts:
      - docker_build_prep.sh
      - docker_tag.sh
    triggers:
      github_push: false
      cron: null
    upstream:
      - eduid-docker-pythonenv
      - eduid-webapp
