publish_over_ssh:
  - pypi.sunet.se
upstream:
  - eduid-userdb
slack:
  room: eduid-builds
pre_build_script:
  - "docker pull docker.sunet.se/library/etcd:v3.3.12"
  - "docker pull docker.sunet.se/eduid/redis:latest"
  - "docker pull docker.sunet.se/eduid/mongodb:latest"
script:
  - "python3.7 -m venv venv"
  - ". venv/bin/activate"
  - "pip install -U pip setuptools wheel mypy"
  - "pip install --index-url https://pypi.sunet.se -r test_requirements.txt"
  - "make test"
  - "make typecheck"
  - "python setup.py sdist bdist_wheel --universal"
clean_workspace: true
