builders:
  - script
triggers:
  cron: "@weekly"
slack:
  room: "eduid-builds"
pre_build_script:
  - "docker pull docker.sunet.se/eduid/mongodb:latest"
script:
  - "python3.7 -m venv venv"
  - ". venv/bin/activate"
  - "pip install -U setuptools wheel mypy"
  - "pip install --index-url https://pypi.sunet.se -r test_requirements.txt"
  - "pip freeze"
  - "pytest"
  - "mypy --ignore-missing-imports eduid_lookup_mobile"
  - "python setup.py sdist bdist_wheel --universal"
publish_over_ssh:
  - pypi.sunet.se
clean_workspace: true

extra_jobs:
  - name: eduid-lookup-mobile-docker
    builders:
      - docker
    docker_name: eduid/eduid-lookup-mobile
    managed_scripts:
      - docker_build_prep.sh
      - docker_tag.sh
    triggers:
      github_push: false
      cron: null
    upstream:
      - eduid-docker-python3env
      - eduid-lookup-mobile

