builders:
  - script
triggers:
  cron: "@weekly"
slack:
  room: "eduid-builds"
pre_build_script:
  - "docker pull docker.sunet.se/eduid/redis:latest"
  - "docker pull docker.sunet.se/eduid/mongodb:latest"
  - "docker pull docker.sunet.se/eduid/smtpdfix:latest"
  - "docker pull neo4j:4.4-enterprise"
  # pillow requires libjpeg and gs
  - "apt-get install -y libjpeg-dev libfreetype6-dev ghostscript libcairo2-dev"
environment_variables:
  NEO4J_VERSION: "4.4-enterprise"
script:
  - "python3.11 -m venv venv"
  - ". venv/bin/activate"
  - "pip install -U pip setuptools wheel mypy"
  - "pip install --index-url https://pypi.sunet.se -r requirements/test_requirements.txt"
  - "pip freeze"
  - "make test"
  - "make typecheck"
clean_workspace: true

extra_jobs:
  - name: eduid-backend-update-deps
    builders:
      - script
    triggers:
      github_push: false
      cron: "@daily"
    script:
      - "python3.11 -m venv venv"
      - ". venv/bin/activate"
      - "pip install -U pip setuptools wheel pip-tools mypy uv"
      - "touch requirements/*in"
      - "make update_deps"
      - "pip install --index-url https://pypi.sunet.se -r requirements/test_requirements.txt"
      - "pip freeze"
      - "make test"
      - "make typecheck"


