builders:
  - python
upstream:
  - eduid-userdb
triggers:
  cron: "@weekly"
slack:
  room: "eduid-builds"
python_module: eduid_msg
python_source_directory: eduid_msg
clean_workspace: true
publish_over_ssh:
  - pypi.sunet.se
