[mypy]
plugins = pydantic.mypy, marshmallow_dataclass.mypy
namespace_packages = True
pretty = True

[mypy-ndnkdf.*]
follow_untyped_imports = True

[mypy-fido_mds.*]
follow_untyped_imports = True

# No stubs available for these packages
[mypy-saml2.*]
ignore_missing_imports = True

[mypy-satosa.*]
ignore_missing_imports = True

[mypy-hammock.*]
ignore_missing_imports = True

[mypy-smscom.*]
ignore_missing_imports = True

[mypy-proquint.*]
ignore_missing_imports = True

[mypy-bcrypt.*]
ignore_missing_imports = True

[mypy-pkcs11.*]
ignore_missing_imports = True

[mypy-pwgen.*]
ignore_missing_imports = True

[mypy-pyhsm.*]
ignore_missing_imports = True

[mypy-statsd.*]
ignore_missing_imports = True

[mypy-suds.*]
ignore_missing_imports = True

[mypy-user_agents.*]
ignore_missing_imports = True

[mypy-apscheduler.*]
ignore_missing_imports = True

[mypy-zeep.*]
ignore_missing_imports = True

[mypy-deepdiff.*]
ignore_missing_imports = True

[mypy-xhtml2pdf.*]
ignore_missing_imports = True

[mypy-cookies_samesite_compat.*]
ignore_missing_imports = True

[mypy-flask_babel.*]
ignore_missing_imports = True

[mypy-marshmallow_enum.*]
ignore_missing_imports = True

[mypy-future.*]
ignore_missing_imports = True
