[mypy]
plugins = pydantic.mypy, marshmallow_dataclass.mypy
namespace_packages = True
pretty = True

[mypy-ndnkdf.*]
follow_untyped_imports = True

[mypy-fido_mds.*]
follow_untyped_imports = True

# No stubs available, too many import sites to pin individually
[mypy-saml2.*]
ignore_missing_imports = True

[mypy-satosa.*]
ignore_missing_imports = True
