[mypy]
plugins = pydantic.mypy, marshmallow_dataclass.mypy
namespace_packages = True
pretty = True
disallow_subclassing_any = True
disallow_untyped_decorators = True
ignore_missing_imports = True
warn_unused_ignores = True

[mypy-ndnkdf.*]
follow_untyped_imports = True

[mypy-fido_mds.*]
follow_untyped_imports = True
