[pytest]
addopts = --import-mode=importlib
python_classes = Test* *Test *Tests
norecursedirs = cookiecutter-app .worktrees
filterwarnings = 
    ignore::DeprecationWarning:saml2.*
    ignore:The SAML service provider accepts unsigned:UserWarning:saml2.*
