@startuml
title ladok

legend
    UNIVERSITIES: {
        [ladok_name]: {ladok_name: str, name: {en: str, sv: str}},
    }

    LADOKDATA: {
            external_id: str, university: {ladok_name: str, name: {sv: str, en: str}}
    }
end legend

Client->"/universities": GET
"/universities"->Client: {"payload":{"universities": UNIVERSITIES}, "type":"GET_LADOK_UNIVERSITIES_SUCCESS"}
|||
Client->"/link-user": POST {ladok_name: str}
alt user linked successfully
"/link-user"->Client: {"payload":{ladok: LADOKDATA}, "type":"POST_LADOK_LINK_USER_SUCCESS"}
else user has no verified nin
"/link-user"->Client: {"payload":{"message": "ladok.no-verified-nin"}, "type":"POST_LADOK_LINK_USER_FAIL"}
else university not found
"/link-user"->Client: {"payload":{"message": "ladok.missing-university"}, "type":"POST_LADOK_LINK_USER_FAIL"}
else user not found in Ladok
"/link-user"->Client: {"payload":{"message": "ladok.no-data-for-user"}, "type":"POST_LADOK_LINK_USER_FAIL"}
end
|||
Client->"/unlink-user": POST {}
"/unlink-user"->Client: {"payload":{"message": "ladok.user-unlinked-successfully"}, "type":"POST_LADOK_UNLINK_USER_SUCCESS"}
@enduml
