@startuml
title login

Client->"/next": POST {"ref": reference}
alt Not logged in
    "/next"->Client: {"payload":{"action": "USERNAMEPASSWORD", "target": "/usernamepw"}, "type":"POST_LOGIN_NEXT_SUCCESS"}
else ToU acceptance required
    "/next"->Client: {"payload":{"action": "TOU", "target": "/tou"}, "type":"POST_LOGIN_NEXT_SUCCESS"}
else MFA required
    "/next"->Client: {"payload":{"action": "MFA", "target": "/mfa"}, "type":"POST_LOGIN_NEXT_SUCCESS"}
else Finished
    "/next"->Client: {"payload":{"action": "FINISHED", "target": "https://..."}, "type":"POST_LOGIN_NEXT_SUCCESS"}
else Login not possible
    "/next"->Client: {"error": true, "payload": {"message": "login.some_error"},"type": "POST_LOGIN_NEXT_FAIL"}
end
|||

Client->"/usernamepw": POST {"ref": reference, "username": username, "password", password}
alt Correct
    "/usernamepw"->Client: {"payload": {"finished": true}, "type": "POST_LOGIN_USERNAMEPW_SUCCESS"}
else Not correct
    "/usernamepw"->Client: {"error": true, "payload": {"message": "login.usernamepw_incorrect}, "type": "POST_LOGIN_USERNAMEPW_FAIL"}
end
|||

Client->"/tou": POST {"ref": reference, "versions": ["2016-v1", "2021-v1"]}
alt Version acceptable to backend present
    "/tou"->Client: {"payload": {"finished": false, "version": version}, "type": "POST_LOGIN_TOU_SUCCESS"}
else No acceptable version present
    "/tou"->Client: {"error": true, "payload": {"message": "login.tou_not_acceptable"},"type": "POST_LOGIN_TOU_FAIL"}
end


Client->"/tou": POST {"ref": reference, "user_accept": true, "version": version}
alt Acceptable
    "/tou"->Client: {"payload": {"finished": true}, "type": "POST_LOGIN_TOU_SUCCESS"}
else Not acceptable
    "/tou"->Client: {"error": true, "payload": {"message": "login.tou_not_acceptable"},"type": "POST_LOGIN_TOU_FAIL"}
end
|||

@enduml
