eduid:
    webapp:
        common:
            # enable disable debug mode
            DEBUG: yes
            # the domain for the session cookie. If this is not set, the cookie will
            # be valid for all subdomains of SERVER_NAME.
            SESSION_COOKIE_DOMAIN: .eduid.docker
            # The URL scheme that should be used for URL generation if no URL scheme is
            # available. This defaults to http
            PREFERRED_URL_SCHEME: http
            # Redis config
            REDIS_HOST: redis.eduid_dev
            # SAML2 and SP config
            SAML2_LOGIN_REDIRECT_URL: /
            SAML2_SETTINGS_MODULE: /opt/eduid/etc/saml2_settings.py
            SAML2_LOGOUT_REDIRECT_URL: http://html.eduid.docker/
            SAML2_USER_MAIN_ATTRIBUTE: eduPersonPrincipalName
            SAML2_STRIP_SAML_USER_SUFFIX: "@local.eduid.se"
            TOKEN_SERVICE_URL: http://authn.eduid.docker:8080/
        authn:
            SERVER_NAME: authn.eduid.docker:8080
            SECRET_KEY: supersecretkey
            MONGO_URI: mongodb://eduid_authn:eduid_authn_pw@mongodb.eduid_dev
            TESTING: no
            LOG_FILE: /opt/eduid/log/authn.log
            LOG_LEVEL: DEBUG
        letter_proofing:
            SECRET_KEY: supersecretkey
            LOG_FILE: /var/log/eduid/letter_proofing.log
            LOG_LEVEL: DEBUG
            MONGO_URI: mongodb://eduid_letter_proofing:eduid_letter_proofing_pw@mongodb.eduid_dev
            # Setting EKOPOST_DEBUG_PDF to a path means that the other EKOPOST settings will be ignored
            # and that the pdf only will be written to to the supplied path, not sent to the letter service.
            EKOPOST_DEBUG_PDF: /opt/eduid/eduid-letter-proofing/run/
            EKOPOST_API_URI: https://api.ekopost.se
            EKOPOST_API_VERIFY_SSL: yes
            EKOPOST_API_USER: ekopost_user
            EKOPOST_API_PW: ekopost_pw
        oidc_proofing:
            SECRET_KEY: supersecretkey
            LOG_FILE: /var/log/eduid/oidc_proofing.log
            LOG_LEVEL: DEBUG
            CLIENT_REGISTRATION_INFO:
                client_id: client1
                client_secret: abcdef
            PROVIDER_CONFIGURATION_INFO:
                issuer: http://localhost:5000
            MONGO_URI: mongodb://eduid_oidc_proofing:eduid_oidc_proofing_pw@mongodb.eduid_dev
        support:
            SECRET_KEY: supersecretkey
            LOG_FILE: /var/log/eduid/support.log
            LOG_LEVEL: DEBUG
            MONGO_URI: mongodb://eduid_support:eduid_support_pw@mongodb.eduid_dev
            STATIC_URL: http://html.eduid.docker/static/
            SUPPORT_PERSONNEL:
              - your-eppn
